export type CategoryKey =
  | 'estucos'
  | 'recubrimientos_decorativos'
  | 'repellos'
  | 'impermeabilizantes'
  | 'adhesivos'
  | 'selladores_barnices'
  | 'pinturas_masillas'

export const CATEGORY_ORDER: CategoryKey[] = [
  'estucos', 'recubrimientos_decorativos', 'repellos',
  'impermeabilizantes', 'adhesivos', 'selladores_barnices', 'pinturas_masillas',
]

export const CATEGORY_LABEL: Record<CategoryKey, string> = {
  estucos: 'Estucos',
  recubrimientos_decorativos: 'Recubrimientos Decorativos',
  repellos: 'Repellos',
  impermeabilizantes: 'Impermeabilizantes',
  adhesivos: 'Adhesivos',
  selladores_barnices: 'Selladores y Barnices',
  pinturas_masillas: 'Pinturas y Masillas',
}

export type CategoryTheme = {
  accent: string; text: string; chipBg: string; chipRing: string
}

export const CATEGORY_THEME: Record<CategoryKey, CategoryTheme> = {
  estucos: { accent: 'bg-black', text: 'text-black', chipBg: 'bg-black', chipRing: 'ring-black/15' },
  recubrimientos_decorativos: { accent: 'bg-emerald-900', text: 'text-emerald-900', chipBg: 'bg-emerald-900', chipRing: 'ring-emerald-900/15' },
  repellos: { accent: 'bg-blue-600', text: 'text-blue-700', chipBg: 'bg-blue-600', chipRing: 'ring-blue-600/15' },
  impermeabilizantes: { accent: 'bg-red-600', text: 'text-red-700', chipBg: 'bg-red-600', chipRing: 'ring-red-600/15' },
  adhesivos: { accent: 'bg-violet-600', text: 'text-violet-700', chipBg: 'bg-violet-600', chipRing: 'ring-violet-600/15' },
  selladores_barnices: { accent: 'bg-amber-600', text: 'text-amber-700', chipBg: 'bg-amber-600', chipRing: 'ring-amber-600/15' },
  pinturas_masillas: { accent: 'bg-orange-500', text: 'text-orange-700', chipBg: 'bg-orange-500', chipRing: 'ring-orange-500/15' },
}

export interface Product {
  id: number
  name: string
  description: string
  price: number
  category: CategoryKey
  stock: number
  image?: string
  galleryImages?: string[]
  sku: string
  technicalSheet?: string
  technicalSummary?: TechnicalSummary
  isNew?: boolean
  hideDetailDescription?: boolean
}

export type TechnicalSummary = {
  rendimiento?: string
  almacenaje?: string
  presentacion?: string
  conservacion?: string
  colores?: string
  usos?: string
  observaciones?: string
  caracteristicas?: string
}

const TECHNICAL_SHEET_BY_ID: Record<number, string> = {
  1:  '/fichas tecnicas/base_floor.pdf',
  2:  '/fichas tecnicas/microtex.pdf',
  3:  '/fichas tecnicas/top_floor.pdf',
  4:  '/fichas tecnicas/concreto_aparente.pdf',
  5:  '/fichas tecnicas/chukum.pdf',
  6:  '/fichas tecnicas/plastercop.pdf',
  7:  '/fichas tecnicas/Estucop_fino.pdf',
  8:  '/fichas tecnicas/Estucop_fino_flex.pdf',
  9:  '/fichas tecnicas/Estucop_fino_acrilico.pdf',
  10: '/fichas tecnicas/alisado.pdf',
  11: '/fichas tecnicas/veneziano.pdf',
  12: '/fichas tecnicas/Albercop.pdf',
  13: '/fichas tecnicas/marmoltex.pdf',
  14: '/fichas tecnicas/textucop.pdf',
  15: '/fichas tecnicas/hormicop.pdf',
  16: '/fichas tecnicas/REPELLO 3 EN 1.pdf',
  17: '/fichas tecnicas/MASILLA FIBRADA.pdf',
  19: '/fichas tecnicas/REPELLO TÉRMICO.pdf',
  21: '/fichas tecnicas/Impermeable de inmersión.pdf',
  22: '/fichas tecnicas/Anti Salitre.pdf',
  23: '/fichas tecnicas/COPELASTIC MONOCOMPONENTE.pdf',
  24: '/fichas tecnicas/Impercop Acrílico.pdf',
  25: '/fichas tecnicas/pega_ceramico.pdf',
  26: '/fichas tecnicas/pega_porcelanato.pdf',
  27: '/fichas tecnicas/pisosobrepiso_flex.pdf',
  28: '/fichas tecnicas/pega_block.pdf',
  29: '/fichas tecnicas/PEGA MARMOL.pdf',
  30: '/fichas tecnicas/Junteador impermeable COP 2.pdf',
  31: '/fichas tecnicas/LACA SOLVENTE.pdf',
  32: '/fichas tecnicas/BARNIZCOP POLIURETÁNICO.pdf',
  33: '/fichas tecnicas/COP SILICÓN BASE AGUA.pdf',
  34: '/fichas tecnicas/COP SILICÓN BASE SOLVENTE.pdf',
  35: '/fichas tecnicas/PLASTICOP.pdf',
  36: '/fichas tecnicas/PLASTIBOND.pdf',
  37: '/fichas tecnicas/SELLACOP INMERSIÓN.pdf',
  38: '/fichas tecnicas/COP ANTIDERRAPANTE.pdf',
  40: '/fichas tecnicas/MASTERCRIL.pdf',
  41: '/fichas tecnicas/ACRILAC 5000H.pdf',
  42: '/fichas tecnicas/ACRILPLUS 7000H.pdf',
  43: '/fichas tecnicas/COPESMALTE.pdf',
  44: '/fichas tecnicas/TRAFICOP.pdf',
  45: '/fichas tecnicas/PINTURA DEPORTIVA.pdf',
  46: '/fichas tecnicas/PINTURA ALBERCAS.pdf',
  47: '/fichas tecnicas/REDIMIX PASTA.pdf',
}

function computeTechnicalSheet(product: Product): string | undefined {
  return TECHNICAL_SHEET_BY_ID[product.id]
}

const IMAGE_BY_ID: Record<number, string> = {
  1:  '/images/base_floor2.png',
  2:  '/images/microtex2.png',
  3:  '/images/top_floor2.png',
  4:  '/images/concreto_aparente.png',
  5:  '/images/chukum.png',
  6:  '/images/plastercop.png',
  7:  '/images/estucop_fino.png',
  8:  '/images/estucop_fino_flex.png',
  9:  '/images/estucop_fino_acrilico2.png',
  10: '/images/alisado.png',
  11: '/images/veneziano2.png',
  12: '/images/albercop.png',
  13: '/images/marmoltex2.png',
  14: '/images/textucop.png',
  15: '/images/hormicop.png',
  16: '/images/repello_3en1.png',
  17: '/images/masilla_fiebrada.png',
  18: '/images/base_copfx.png',
  19: '/images/repello_termico.png',
  20: '/images/repello_impermeable.png',
  21: '/images/impermeable_de_inmersion_1.png',
  22: '/images/anti_salitre_1.png',
  23: '/images/copelastic_monocomponente.png',
  24: '/images/impercop_acrilico.png',
  25: '/images/pega_ceramico.png',
  26: '/images/pega_porcelanato_1.png',
  27: '/images/piso_sobre_piso_flex.png',
  28: '/images/pega_block_1.png',
  29: '/images/pega_marmol_1.png',
  30: '/images/juntador_impermeable_cop.png',
  31: '/images/LACA SOLVENTE2.png',
  32: '/images/barnizcop_poliuretanico.png',
  33: '/images/cop_silicon_base_agua2.png',
  34: '/images/cop_silicon_base_solvente2.png',
  35: '/images/plasticop2.png',
  36: '/images/plastibond2.png',
  37: '/images/SELLACOP INMERSION2.png',
  38: '/images/antiderrapante_cop2.png',
  39: '/images/INTERCRIL2.png',
  40: '/images/mastercril2.png',
  41: '/images/ACRILAC 5000H.png',
  42: '/images/acrilplus_7000.2.png',
  43: '/images/cop_esmalte2.png',
  44: '/images/traficop2.png',
  45: '/images/pintura_deportiva2.png',
  46: '/images/pintura_albercas2.png',
  47: '/images/rendimix_pasta.png',
  48: '/images/rendimix_seco.png',
}

const TECHNICAL_SUMMARY_BY_ID: Record<number, TechnicalSummary> = {
  1: {
    rendimiento: "5 a 6 m2 a 3 mm de espesor",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde de 20 kg.",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "gris y crema",
    usos: "Aplicación sobre firmes cementicios, placas de yeso, concreto, porcelanatos y azulejos existentes (previamente sellados con PLASTICOP 1000)",
    caracteristicas: "Gran flexibilidad. Alta adherencia. Granulometría óptima. Excelente tiempo abierto. Gran dureza.",
    observaciones: "• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar con sol directo sobre el paño.\n• No aplicar con exposición a fuertes vientos.\n• No aplicar sobre paredes con humedad.",
  },
  2: {
    rendimiento: "25 m2 por Balde de 32 kg a 3 mm de espesor",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde de 37 kg",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "Mercurio, Plomo, Marfil y chukum",
    usos: "Aplicación sobre BASE FLOOR, BASECOP, repello 3 en 1 COP, masilla COP, placas de cartón, yeso, fibrocemento previamente sellado con PLASTIBOND",
    caracteristicas: "Gran resistencia. Impermeable. Flexible. Recubre imperfecciones. Durabilidad del color a largo plazo. Listo para usar. Ideal para renovaciones rápidas.",
    observaciones: "• Después de colocar MICROTEX, aplicar LACA POLIURETÁNICA COP.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes o pisos con humedad.",
  },
  3: {
    rendimiento: "4 m2 por Balde de 20 kg",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde de 20 kg.",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    usos: "Aplicación sobre BASE FLOOR, BASECOP, repello 3 en 1 COP, masilla COP, placas de cartón, yeso, fibrocemento previamente sellado con PLASTIBOND.",
    caracteristicas: "Gran resistencia. Impermeable. Flexible. Recubre imperfecciones. Durabilidad del color a largo plazo. Listo para usar. Ideal para renovaciones rápidas.",
    observaciones: "• Después de colocar TOP FLOOR, aplicar LACA POLIURETÁNICA COP.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes o pisos con humedad.",
  },
  4: {
    rendimiento: "12 a 15 m2 a 2 mm de espesor por Bolsa de 20 kg",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg.",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "Gris natural, Gris concreto y Gris Coliseo",
    usos: "Aplicación sobre BASECOP, repello 3 en 1 COP, masilla COP, placas de cartón, yeso, fibrocemento previamente sellado con PLASTIBOND",
    caracteristicas: "Gran estética. Óptima resistencia. Flexible. Durabilidad del color a largo plazo.",
    observaciones: "• Después de la colocación, aplicar LACA POLIURETÁNICA o COP SILICON.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes o pisos con humedad.",
  },
  5: {
    rendimiento: "12 a 15 m2 a 2 mm de espesor por Bolsa de 20 kg",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg.",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "Chukum natural, Chukum Hacienda, Chukum Maya",
    usos: "Aplicación sobre BASECOP, repello 3 en 1 COP, masilla COP, placas de cartón, yeso, fibrocemento previamente sellado con PLASTIBOND",
    caracteristicas: "Gran estética. Óptima resistencia. Flexible. Durabilidad del color a largo plazo.",
    observaciones: "• Después de la colocación, aplicar LACA POLIURETÁNICA o COP SILICON.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes o pisos con humedad.",
  },
  6: {
    rendimiento: "12 a 15 m2 a 2 mm de espesor por Bolsa de 20 kg",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg.",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "Ver carta de colores",
    usos: "Aplicación sobre BASECOP, repello 3 en 1 COP, masilla COP, placas de cartón, yeso, fibrocemento previamente sellado con PLASTIBOND",
    caracteristicas: "Gran estética. Óptima resistencia. Flexible. Durabilidad del color a largo plazo.",
    observaciones: "• Después de la colocación, aplicar LACA POLIURETÁNICA o COP SILICON.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes o pisos con humedad.",
  },
  7: {
    rendimiento: "12 a 15 m2 a 2 mm de espesor por Bolsa de 20 kg",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg.",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "gris, crema y blanco",
    usos: "Aplicación sobre BASECOP, repello 3 en 1 COP, masilla COP, placas de cartón, yeso, fibrocemento previamente sellado con PLASTIBOND",
    caracteristicas: "Gran estética. Óptima resistencia. Durabilidad del color a largo plazo.",
    observaciones: "• Después de la colocación, aplicar LACA POLIURETÁNICA o COP SILICON.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes o pisos con humedad.",
  },
  8: {
    rendimiento: "12 a 15 m2 a 2 mm de espesor por Bolsa de 20 kg",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg.",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "gris, crema y blanco",
    usos: "Aplicación sobre BASECOP, repello 3 en 1 COP, masilla COP, placas de cartón, yeso, fibrocemento previamente sellado con PLASTIBOND",
    caracteristicas: "Gran estética. Óptima resistencia. Durabilidad del color a largo plazo.",
    observaciones: "• Después de la colocación, aplicar LACA POLIURETÁNICA o COP SILICON.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes o pisos con humedad.",
  },
  9: {
    rendimiento: "25 m2 por Balde de 32 kg a 3 mm de espesor",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde de 32 kg y galón5KG",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "crema, blanco y 30 colores de línea",
    usos: "Aplicación sobre BASECOP, repello 3 en 1 COP, masilla COP, placas de cartón, yeso, fibrocemento previamente sellado con PLASTIBOND",
    caracteristicas: "Gran resistencia. Impermeable. Flexible. Recubre imperfecciones. Durabilidad del color a largo plazo. Listo para usar. Ideal para renovaciones rápidas.",
    observaciones: "• Después de la colocación, aplicar LACA POLIURETÁNICA o COP SILICON.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes o pisos con humedad.",
  },
  10: {
    rendimiento: "12 a 15 m2 a 2 mm de espesor por Bolsa de 20 kg",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg.",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "girs, crema y blanco",
    usos: "Aplicación sobre BASECOP, repello 3 en 1 COP, masilla COP, placas de cartón, yeso, fibrocemento previamente sellado con PLASTIBOND",
    caracteristicas: "Gran estética. Granulometría óptima. Gran dureza. Durabilidad del color a largo plazo.",
    observaciones: "• Después de la colocación, aplicar PINTURA COP.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes o pisos con humedad.",
  },
  11: {
    rendimiento: "15 m2 por balde de 5 kg a tres manos",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Galón",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "30 colores de línea",
    usos: "Aplicación sobre ESTUCOP FINO BLANCO sellado previamente con PLASTIBOND.",
    caracteristicas: "Alto brillo. De fácil aplicación. Listo para usar. Protege la superficie cubriendo las micro fisuras existentes en el repello. No acumula polvo.",
    observaciones: "• Usar llana de punta redonda “llana italiana”.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar sobre paredes con humedad.\n• En exterior, sellar con laca COP.",
  },
  12: {
    rendimiento: "4 m2 a  6 mm de espesor por Bolsa de 20 kg",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "natural y chukum",
    usos: "Aplicación sobre concreto, block, aplanado grueso previamente sellado con PLASTICOP",
    caracteristicas: "Gran impermeabilidad. Alta adherencia. Finura óptima. Excelente tiempo abierto. Gran resistencia en inmersión. Durabilidad del color a largo plazo.",
    observaciones: "• Aplicar de 6 mm a 1 cm de espesor en capas.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes con humedad.",
  },
  13: {
    rendimiento: "Grano grueso: 10 - 12 m2 por Balde de 32 kg\nGrano medio: 12 - 14 m2 por Balde de 32 kg\nGrano fino: 16 - 18 m2 por Balde de 32 kg",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde de 32 kg",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "33 colores de línea",
    usos: "Aplicación sobre BASECOP, repello 3 en 1 COP, masilla COP, placas de cartón, yeso, fibrocemento previamente sellado con PLASTIBOND COLOR",
    caracteristicas: "Gran resistencia a la interperie. Impermeable. Flexible. Recubre imperfecciones. Durabilidad del color a largo plazo.",
    observaciones: "• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No humedecer la llana plástica para evitar eflorescencias.\n• No aplicar sobre paredes con humedad.",
  },
  14: {
    rendimiento: "6 a 7 m2 a 3mm de espesor",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg.",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "gris, crema, blanco",
    usos: "Aplicación sobre BASECOP, repello 3 en 1 COP, masilla COP, placas de cartón, yeso, fibrocemento previamente sellado con PLASTIBOND COLOR",
    caracteristicas: "Gran resistencia a los agentes atmosféricos. Hidrófugo. Recubre imperfecciones. Durabilidad. Dureza.",
    observaciones: "• Realizar paños completos para evitar empalmes.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar con sol directo sobre el paño.\n• No aplicar con exposición a fuertes vientos.\n• No humedecer la llana plástica o fratacho para evitar\neflorescencias del agua en el revestimiento.\n• No apto para muros de construcción en seco.\n• No aplicar sobre paredes con humedad.",
  },
  15: {
    rendimiento: "8 m2 por bolsa de 20 kg",
    almacenaje: "Almacenar en su envase original\ny herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "gris natural, crema y gris oscuro",
    usos: "Se puede usar en interior y exterior, sobre soportes a base\nde cementos: hormigones, concretos, masilla COP, repello 3 en 1 COP y  repello grueso.",
    caracteristicas: "Gran estetica simil hormigon, alta dureza, facil aplicación, gran flexibilidad",
    observaciones: "• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar con sol directo sobre el paño.\n• No aplicar con exposición a fuertes vientos.\n• No aplicar sobre paredes con humedad.",
  },
  16: {
    rendimiento: "1 a 1.25 m2  a 1 cm de espesor por Bolsa de 20 kg.  Como acabado final sobre repello grueso\naproximadamente 5 m2 por Bolsa de 20 kg",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg.",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "gris, crema, blanco",
    usos: "Aplicación sobre block ó repello grueso  (previamente sellado con PLASTIBOND)",
    caracteristicas: "Hidrófugo. Adherencia. Finura óptima. Excelente tiempo abierto. No cuartea",
    observaciones: "• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes con humedad.\n• No aplicar en muros de construcción en seco.",
  },
  17: {
    rendimiento: "4.5 m2 por Bolsa de 20 kg",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg.",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "gris, crema, blanco",
    usos: "Aplicacion sobre repello grueso.",
    caracteristicas: "Facil de aplicar. Aplicacion manual. Finura optima. No cuartea",
    observaciones: "• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes con humedad.\n• No aplicar en muros de construcción en seco.",
  },
  18: {
    rendimiento: "6 a 8 m2 a 3 mm de espesor por Bolsa de 20 kg",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg.",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "gris y blanco",
    usos: "Aplicación sobre paneles de poliestireno, placas de yeso, bloques de hormigón celular y repello grueso previamente sellado con PLASTIBOND.",
    caracteristicas: "Gran flexibilidad. Alta adherencia. Finura óptima. Excelente tiempo abierto.",
    observaciones: "• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar con sol directo sobre el paño.\n• No aplicar con exposición a fuertes vientos.\n• No aplicar sobre paredes con humedad.",
  },
  19: {
    rendimiento: "1 a 1.25 m2  a 1 cm de espesor por Bolsa de 20 kg.  Como acabado final sobre repello grueso\naproximadamente 5 m2 por Bolsa de 20 kg",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg.",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "gris, blanco y crema",
    usos: "Aplicación sobre block ó repello grueso  (previamente sellado con PLASTIBOND)",
    caracteristicas: "Gran aislamiento térmico. Excelente dureza. Buena trabajabilidad",
    observaciones: "• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar con sol directo sobre el paño.\n• No aplicar con exposición a fuertes vientos.\n• No aplicar sobre paredes con humedad.",
  },
  20: {
    rendimiento: "1 a 1.25 m2  a 1 cm de espesor por Bolsa de 20 kg.  Como acabado final sobre repello grueso\naproximadamente 5 m2 por Bolsa de 20 kg",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg.",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "gris, blanco y crema",
    usos: "Aplicación sobre block ó repello grueso  (previamente sellado con PLASTIBOND)",
    caracteristicas: "Excelente impermeabilidad, dureza optima, gran resistencia a la intemeprie",
    observaciones: "• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar con sol directo sobre el paño.\n• No aplicar con exposición a fuertes vientos.\n• No aplicar sobre paredes con humedad.",
  },
  21: {
    rendimiento: "5  m2 a 3 mm de espesor por Bolsa de 20 kg",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "gris",
    usos: "Impermeabilizaciones de losas, cubiertas, balcones, duchas, albercas, terrazas, jardineras y cisternas. Diseñado para estar en inmersión en constante contacto con el agua.",
    caracteristicas: "Alta resistencia a la interperie. Impermeabilizacion en inmersión. Gran adherencia. Excelente resistencia final.",
    observaciones: "• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar con sol directo sobre el paño.\n• No aplicar con exposición a fuertes vientos.\n• No aplicar sobre paredes con humedad.",
  },
  22: {
    rendimiento: "5 m2 a 3 mm de espesor por Bolsa de 20 kg",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "gris",
    usos: "Se utiliza para la prevención o reparación de superficies donde exista la presencia de eflorescencia o salitre. Se aplica directamente al sustrato original en espesores de 3 mm hasta 1 cm.",
    caracteristicas: "Evita aparición de efloresencia. No permite el paso de humedad por capilaridad. Alta impermeabilidad. Óptima dureza final.",
    observaciones: "• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes con humedad.\n• No aplicar en muros de construcción en seco.",
  },
  23: {
    rendimiento: "5 m2 por Bolsa de 20 kg",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "gris",
    usos: "Uso en cisternas, techos, terrazas, baños, jardineras y juntas constructivas (colocando malla fibra de vidrio 130 grms)",
    caracteristicas: "Alta impermeabilidad. Ultra Flexibilidad. Resistencia a la intemperie. Máxima dureza.",
    observaciones: "• Si se aplica con llana, usar malla fibra de vidrio 120 gr.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes o pisos con humedad.",
  },
  24: {
    rendimiento: "20 m2 por Balde de 19 lt",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde de 19 lt",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "blanco, rojo terracota y verde inglés",
    usos: "Aplicación sobre techos, lámina y terrazas asi como paredes exteriores que requieran protección extra. (Sugerimos utilizar con malla poliester multidireccional para mejores resultados)",
    caracteristicas: "Alta impermeabilidad. Ultra Flexibilidad. Resistencia a la intemperie. Máxima dureza. Facil aplicacion.",
    observaciones: "Diluir con un 10 % de agua en caso de ser necesario.\n• No agregar ningún otro componente.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar con sol directo sobre el paño.\n• No aplicar con exposición a fuertes vientos.\n• No aplicar sobre paredes con humedad.",
  },
  25: {
    rendimiento: "Llana 1/4\" x 1/4\" x 1/4\" (6.35 mm) 5-6 m2 Llana 3/8\" x 3/8\" x 3/8\" (9.5 mm) 4-4.5 m2 Llana 1/2\" x 1/2\" x 1/2\" (12.7 mm) 2-3 m2",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "gris",
    usos: "Colocación de piezas cerámicas de alta absorción sobre fiemes o repellos interiores.",
    caracteristicas: "Adherencia. Granulometria óptima. Excelente tiempo abierto. Gran dureza final.",
    observaciones: "• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar con sol directo sobre el paño.\n• No aplicar con exposición a fuertes vientos.\n• No aplicar sobre paredes con humedad.\n• Respetar el agua de amasado: 5 L por bolsa.\n• Si el soporte es muy absorbente o está en exposición directa al sol, con altas temperaturas, humedecer levemente el soporte.\n• Comprobar la pegajosidad de la pasta extendida antes de colocar la pieza.",
  },
  26: {
    rendimiento: "Llana 1/4\" x 1/4\" x 1/4\" (6.35 mm) 5-6 m2 Llana 3/8\" x 3/8\" x 3/8\" (9.5 mm) 4-4.5 m2 Llana 1/2\" x 1/2\" x 1/2\" (12.7 mm) 2-3 m2",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "gris",
    usos: "Colocación de porcelanatos en pisos y paredes interiores o exteriores.",
    caracteristicas: "Adherencia. Granulometria óptima. Excelente tiempo abierto. Gran dureza final.",
    observaciones: "• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar con sol directo sobre el paño.\n• No aplicar con exposición a fuertes vientos.\n• No aplicar sobre paredes con humedad.\n• Respetar el agua de amasado: 5 L por bolsa.\n• Si el soporte es muy absorbente o está en exposición directa al sol, con altas temperaturas, humedecer levemente el soporte.\n• Comprobar la pegajosidad de la pasta extendida antes de colocar la pieza.",
  },
  27: {
    rendimiento: "Llana 1/4\" x 1/4\" x 1/4\" (6.35 mm) 5-6 m2 Llana 3/8\" x 3/8\" x 3/8\" (9.5 mm) 4-4.5 m2 Llana 1/2\" x 1/2\" x 1/2\" (12.7 mm) 2-3 m2",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "gris",
    usos: "Colocación de grandes formatos ceramicos o porcelanatos para pisos y paredes exteriores e interiores ó colocación de piezas sobre pisos existentes sin necesidad de retirar el anterior.",
    caracteristicas: "Adherencia. Granulometria óptima. Excelente tiempo abierto. Gran dureza final.",
    observaciones: "• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar con sol directo sobre el paño.\n• No aplicar con exposición a fuertes vientos.\n• No aplicar sobre paredes con humedad.\n• Respetar el agua de amasado: 5 L por bolsa.\n• Si el soporte es muy absorbente o está en exposición directa al sol, con altas temperaturas, humedecer levemente el soporte.\n• Comprobar la pegajosidad de la pasta extendida antes de colocar la pieza.",
  },
  28: {
    rendimiento: "3 a 4  m2 por Bolsa de 20 kg",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "gris",
    usos: "Colocación de block, ladrillo arcilla en muros interiores y exteriores no estructurales.",
    caracteristicas: "Adherencia. Granulometria óptima. Excelente tiempo abierto. Gran dureza final.",
    observaciones: "• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar con sol directo sobre el paño.\n• No aplicar con exposición a fuertes vientos.\n• No aplicar sobre paredes con humedad.\n• Respetar el agua de amasado: 5 L por bolsa.\n• Si el soporte es muy absorbente o está en exposición directa al sol, con altas temperaturas, humedecer levemente el soporte.\n• Comprobar la pegajosidad de la pasta extendida antes de colocar la pieza.",
  },
  29: {
    rendimiento: "Llana 1/4\" x 1/4\" x 1/4\" (6.35 mm) 5-6 m2 Llana 3/8\" x 3/8\" x 3/8\" (9.5 mm) 4-4.5 m2 Llana 1/2\" x 1/2\" x 1/2\" (12.7 mm) 2-3 m2",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "gris",
    usos: "Colocación de marmól de pequeño formato en paredes y pisos exteriores e interiores",
    caracteristicas: "Adherencia. Granulometria óptima. Excelente tiempo abierto. Gran dureza final.",
    observaciones: "• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar con sol directo sobre el paño.\n• No aplicar con exposición a fuertes vientos.\n• No aplicar sobre paredes con humedad.\n• Respetar el agua de amasado: 5 L por bolsa.\n• Si el soporte es muy absorbente o está en exposición directa al sol, con altas temperaturas, humedecer levemente el soporte.\n• Comprobar la pegajosidad de la pasta extendida antes de colocar la pieza.",
  },
  30: {
    rendimiento: "El rendimiento depende de la abertura y profundidad de ranura que se desee resanar. Aproximado 3mm es de 25 a 30 m2 por bolsa de 20 kg., de 12 a 15 m2 por bolsa de 10 kg., de 6 a 7 m2 por bolsa de 5 kg., de 1.2 a 1.5 m2 por bolsa de 1 kg.",
    presentacion: "Bolsa de 20 kg, 10 kg, 5 kg y 1 kg",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "blanco, gris natural y gris oscuro",
    usos: "Relleno de juntas entre piezas cerámicas, pisos y azulejos.",
    caracteristicas: "Adherencia. Granulometria óptima. Excelente tiempo abierto. Gran dureza final.",
    observaciones: "• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar con sol directo sobre el paño.\n• No aplicar con exposición a fuertes vientos.\n• No aplicar sobre paredes con humedad.\n• Respetar el agua de amasado: 6 L por bolsa.\n• Si el soporte es muy absorbente o está en exposición directa al sol, con altas temperaturas, humedecer levemente el soporte.",
  },
  31: {
    rendimiento: "entre 80 y 100 m2 por Balde de 19 lt\nentre 20 y 25 m2 por galón",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde 19 lts\ngalón",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "semi viscoso transparente",
    usos: "Para aplicaciones sobre superficies de concreto estampado. Puede usarse para sellar y abrillantar piezas de barro como pisos, piedras, tejas o elementos decorativos. Cuando se coloca sobre las juntas de  piezas cerámicas otorga un aspecto abrillantado y disminuye la absorción de agua. Puede utilizarse para realzar muros de ladrillo, block visto o muros con aplanados o texturizados",
    caracteristicas: "Muy fácil aplicación,abrillanta supercifies,protege contra sales y rayos UV",
    observaciones: "• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes con humedad.",
  },
  32: {
    rendimiento: "entre 80 y 100 m2 por Balde de 19 lt\nentre 20 y 25 m2 por galón",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde 19 lts\ngalón",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "transparente",
    usos: "Aplicación en revestimientos cementicios, acrilicos, piedras naturales y madera. Sobre TOP FLOOR,MICROTEX, PLASTERCOP, CONCRETO APARENTE, CHUKUM, ESTUCOP FINO en paredes y pisos exteriores e interiores que requieran resistencia a la abrasión y al manchado sin otorgar brillo o su versión LACA POLIURETÁNICA BRILLOSA que otorga brillo ligero",
    caracteristicas: "Secado rápido, Inoloro, Fácil aplicación, Ideal para proteger micro cementos, estucados y maderas",
    observaciones: "• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes con humedad.",
  },
  33: {
    rendimiento: "10 m2 por litro a una mano",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde 19 lts\ngalón",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "transparente",
    usos: "Aplicación sobre PLASTERCOP, CHUKUM, CONCRETO APARENTE, ESTUCOP FINO estucados cementicios, ladrillos vistos, tejas, piedras naturales y hormigón visto.",
    caracteristicas: "Impide la formación de hongos. Protege de la humedad superficial. Impide eflorescencias salinas. No forma película.\nNo modifica el aspecto de la superficie.No genera brillo.No es pegajoso al tacto. Secado rápido",
    observaciones: "• No diluir con agua ni agregar componentes.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes con humedad.",
  },
  34: {
    rendimiento: "10 m2 por litro a una mano",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde 19 lts\ngalón",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "transparente",
    usos: "Aplicación sobre PLASTERCOP, CHUKUM, CONCRETO APARENTE, ESTUCOP FINO estucados cementicios, ladrillos vistos, tejas, piedras naturales y hormigón visto.",
    caracteristicas: "Impide la formación de hongos. Protege de la humedad superficial. Impide eflorescencias salinas. No forma película.\nNo modifica el aspecto de la superficie.No genera brillo.No es pegajoso al tacto. Secado rápido",
    observaciones: "• No diluir con agua ni agregar componentes.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes con humedad.",
  },
  35: {
    rendimiento: "2 a 2.5 m2 por litro",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde 19 lts\ngalón",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "azul",
    usos: "Aplicacion sobre superficies como repellos, firmes, concretos, hormigones, estucos, panelería ligera o cualquier superficie lisa que necesite ser recubierta",
    caracteristicas: "Gran adherencia a superficies lisas. Evita tener que picar la superficie.",
    observaciones: "• No diluir con agua ni agregar componentes.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes con humedad.",
  },
  36: {
    rendimiento: "8 a 10 m2 por litro",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde 19 lts\ngalón",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "transparente",
    usos: "Aplicacion sobre superficies como repellos, firmes, concretos, hormigones, estucos, panelería ligera o cualquier superficie que necesite ser sellada",
    caracteristicas: "Mejora la adherencia. Favorece el tiempo abierto de los revestimientos.",
    observaciones: "• Diluir 1 parte de agua por 1 parte del producto.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes con humedad.",
  },
  37: {
    rendimiento: "10 m2 por litro a una mano",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde 19 lts\ngalón",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "semi viscoso transparente",
    usos: "Aplicacion sobre superficies como repellos, firmes, concretos, hormigones, estucados, panelería ligera o cualquier superficie que necesite ser sellada",
    caracteristicas: "Secado rápido, Inoloro, Fácil aplicación, Ideal para proteger contra hongos y algas.",
    observaciones: "• Diluir 1 parte de agua por 1 parte del producto.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes con humedad.",
  },
  38: {
    rendimiento: "2 a 2.5 m2 por litro",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde 19 lts\ngalón",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "semi viscoso transparente",
    usos: "Aplicacion sobre superficies lisas como piezas ceramicas, micro cementos, bordes de albercas, escaleras, terrazas, jardines, balcones",
    caracteristicas: "Secado rápido, Inoloro, Fácil aplicación, Ideal para superficies resbaladizas",
    observaciones: "• No diluir con agua ni agregar componentes.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes con humedad.",
  },
  39: {
    rendimiento: "2.5 - 3 m2 por litro a 2 manos",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde 19 lts\ngalón",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "Ver carta de colores",
    caracteristicas: "Uso interior. Buen poder cubritivo. Durabilidad.\n.",
  },
  40: {
    rendimiento: "3-4 m2 por litro a 2 manos",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde 19 lts\ngalón",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "Ver carta de colores",
    usos: "Aplicación sobre REPELLO 3 EN 1, MASILLA COP, ESTUCOP FINO BLANCO, ESTUCOP FINO GRIS,  yeso, fibrocemento y panelería ligera  previamente sellado con PLASTIBOND.",
    caracteristicas: "*gran poder cubritivo * mayor velocidad de obra * ideal para placas de yeso-cartón  * óptima resistencia a la intemperie",
    observaciones: "• Diluir con un 10% de agua si es necesario.\n• No agregar ningún otro componente.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar sobre paredes con humedad.",
  },
  41: {
    rendimiento: "3-4 m2 por litro a 2 manos",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde 19 lts\ngalón",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "Ver carta de colores",
    usos: "Aplicación sobre REPELLO 3 EN 1, MASILLA COP, ESTUCOP FINO BLANCO, ESTUCOP FINO GRIS,  yeso, fibrocemento y panelería ligera . Se recomienda no sellar la superficie para no interferir con sus propiedades impermeables",
    caracteristicas: "*gran poder cubritivo *anti- humedad- * anti hongos  * óptima resistencia a la intemperie",
    observaciones: "• Diluir con un 10% de agua si es necesario.\n• No agregar ningún otro componente.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar sobre paredes con humedad.",
  },
  42: {
    rendimiento: "3-4 m2 por litro a 2 manos",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde 19 lts\ngalón",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "Ver carta de colores",
    usos: "Aplicación sobre REPELLO 3 EN 1, MASILLA COP, ESTUCOP FINO BLANCO, ESTUCOP FINO GRIS,  yeso, fibrocemento y panelería ligera . Se recomienda no sellar la superficie para no interferir con sus propiedades impermeables",
    caracteristicas: "*gran poder cubritivo *anti- humedad- * anti hongos  * Destacada resistencia a la intemperie",
    observaciones: "• Diluir con un 10% de agua si es necesario.\n• No agregar ningún otro componente.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar sobre paredes con humedad.",
  },
  43: {
    rendimiento: "2-3 m2 por litro a 2 manos",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde 19 lts\ngalón",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "Ver carta de colores",
    usos: "Aplicar en superficies metálicas previamente preparadas y limpias. Proporciona protección para: puertas, ventanas, molduras, contraventanas, enrejados, puertas de cocheras, barandillas y herrería en general",
    caracteristicas: "Ressitencia a luz ultravioleta, anti corrosivo, Secado rapido, resistencia a la intemperie",
    observaciones: "• Limpiar la superficie de óxido y residuos antes de aplicar.\n• El metal al descubierto debe pintarse el mismo día que se limpia.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.",
  },
  44: {
    rendimiento: "3-4 m2 por litro a 2 manos",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde 19 lts\ngalón",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "Ver carta de colores",
    usos: "Se recomienda su uso para señalizaciones, líneas laterales o centrales, pasos peatonales, estacionamientos y demarcación vial en general.",
    caracteristicas: "*Secado rápido. *amigable con el medio ambiente. *alto poder cubritivo. * resistencia al paso vehicular e intemperie * excelente adherencia",
    observaciones: "• En superficies nuevas de concreto esperar 28 días de fraguado.\n• Lavar con solución de ácido muriático al 10% antes de pintar.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar sobre superficies con humedad.",
  },
  45: {
    rendimiento: "3-4 m2 por litro a 2 manos",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde 19 lts\ngalón",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "Ver carta de colores",
    usos: "Se recomienda su uso para señalizaciones, líneas laterales o centrales, pasos peatonales, estacionamientos y demarcación vial en general.",
    caracteristicas: "* Antiderrapante *Secado rápido. *amigable con el medio ambiente. *alto poder cubritivo. * resistencia al uso rudo* excelente adherencia",
    observaciones: "• En superficies nuevas de concreto esperar 28 días de fraguado.\n• Lavar con solución de ácido muriático al 10% antes de pintar.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar sobre superficies con humedad. \"",
  },
  46: {
    rendimiento: "3-4 m2 por litro a 2 manos",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde 19 lts\ngalón",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "Ver carta de colores",
    usos: "Aplicación en albercas de recubrimientos cementicios ó concreto. Se puede emplear para superficies expuestas a alta humedad. Se recomienda colocar sobre IMPERMEABLE INMERSIÓN COP.",
    caracteristicas: "* Impermeable en inmersión *Secado rápido. *amigable con el medio ambiente. *Flexible* excelente adherencia.",
    observaciones: "• En superficies nuevas de concreto esperar 28 días de fraguado.\n• Lavar con solución de ácido muriático al 10% antes de pintar.\n• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar sobre superficies con humedad. \"",
  },
  47: {
    rendimiento: "Rendimiento: 0.80 kg por m2",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Balde 28 kg",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "blanco",
    usos: "Este producto se utiliza sobre cualquier sistema de muro o plafón en placas de cartón-yeso, en obras nuevas o remodelaciones. Este producto garantiza una excelente adherencia de la cinta de refuerzo para juntas perfacinta al tablero de yeso, dándole una gran resistencia al agrietamiento así como una mejor adhesión.",
    caracteristicas: "Perfecta Adherencia. Finura óptima. Dureza final. Fácil lijado. Óptima Trabajabilidad.",
    observaciones: "• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes con humedad.",
  },
  48: {
    rendimiento: "12 a 15 m2 a 2 mm de espesor por Bolsa de 20 kg",
    almacenaje: "Envase original herméticamente cerrado.",
    presentacion: "Bolsa de 20 kg.",
    conservacion: "12 meses a partir de la fecha de fabricación.",
    colores: "blanco",
    usos: "Este producto se utiliza sobre cualquier sistema de muro o plafón en placas de cartón-yeso, en obras nuevas o remodelaciones. Este producto garantiza una excelente adherencia de la cinta de refuerzo para juntas perfacinta al tablero de yeso, dándole una gran resistencia al agrietamiento así como una mejor adhesión.",
    caracteristicas: "Perfecta Adherencia. Finura óptima. Dureza final. Fácil lijado. Óptima Trabajabilidad.",
    observaciones: "• No aplicar con temperaturas inferiores a los 5° y/o superiores a los 30°.\n• No aplicar con pronóstico de lluvia o heladas.\n• No aplicar sobre paredes con humedad.",
  },
}

const RAW_PRODUCTS = [
  {
    id: 1,
    name: "BASE FLOOR",
    description: "Mortero cementicio de gran dureza y flexibilidad para la nivelación de firmes y barras de concreto previo a la colocación de MICROTEX ó TOP FLOOR cementicio",
    price: 0,
    category: 'estucos' as CategoryKey,
    stock: 99,
    sku: 'MX001',
  },
  {
    id: 2,
    name: "MICROTEX",
    description: "Recubrimiento estucado acrílico para decorar y proteger pisos y paredes.",
    price: 0,
    category: 'estucos' as CategoryKey,
    stock: 99,
    sku: 'MX002',
  },
  {
    id: 3,
    name: "TOP FLOOR",
    description: "Recubrimiento estucado cementicio para decorar y proteger pisos y paredes.",
    price: 0,
    category: 'estucos' as CategoryKey,
    stock: 99,
    sku: 'MX003',
  },
  {
    id: 4,
    name: "Concreto Aparente",
    description: "Recubrimiento estucado cementicio imitación cemento pulido para decorar y proteger paredes exteriores e interiores",
    price: 0,
    category: 'estucos' as CategoryKey,
    stock: 99,
    sku: 'MX004',
  },
  {
    id: 5,
    name: "CHUKUM",
    description: "Recubrimiento estucado cementicio imitación \"estuco maya\" color chukum para decorar y proteger paredes exteriores e interiores",
    price: 0,
    category: 'estucos' as CategoryKey,
    stock: 99,
    sku: 'MX005',
  },
  {
    id: 6,
    name: "PLASTERCOP",
    description: "Recubrimiento estucado cementicio con color integrado imitación cemento pulido para decorar y proteger paredes exteriores e interiores",
    price: 0,
    category: 'estucos' as CategoryKey,
    stock: 99,
    sku: 'MX006',
  },
  {
    id: 7,
    name: "Estucop Fino",
    description: "Recubrimiento cementicio para decorar y proteger paredes exteriores e interiores realizando un \"acabado espejo\"",
    price: 0,
    category: 'estucos' as CategoryKey,
    stock: 99,
    sku: 'MX007',
  },
  {
    id: 8,
    name: "Estucop Fino Flex",
    description: "Recubrimiento cementicio flexible para emplearse en muros y plafones de tablaroca y tablacemento en interiores y exteriores.",
    price: 0,
    category: 'estucos' as CategoryKey,
    stock: 99,
    sku: 'MX008',
  },
  {
    id: 9,
    name: "Estucop Fino Acrílico",
    description: "Revestimiento estucado acrílico para decorar y proteger paredes exteriores e interiores.",
    price: 0,
    category: 'estucos' as CategoryKey,
    stock: 99,
    sku: 'MX009',
  },
  {
    id: 10,
    name: "Alisado",
    description: "Pasta fina cementicia para afinar repellos y masillas en muros exteriores e interiores.",
    price: 0,
    category: 'estucos' as CategoryKey,
    stock: 99,
    sku: 'MX010',
  },
  {
    id: 11,
    name: "Veneziano",
    description: "Recubrimiento brillante imitación mármol de gran durabilidad y belleza para muros interiores y exteriores.",
    price: 0,
    category: 'estucos' as CategoryKey,
    stock: 99,
    sku: 'MX011',
  },
  {
    id: 12,
    name: "Albercop",
    description: "Mortero cementicio impermeable y de gran resistencia para uso en interiores y exteriores en pisos, piscinas, duchas, jacuzzis, fuentes y estanques.",
    price: 0,
    category: 'recubrimientos_decorativos' as CategoryKey,
    stock: 99,
    sku: 'MX012',
  },
  {
    id: 13,
    name: "Marmoltex",
    description: "Recubrimiento acrílico texturizado para decorar e impermeabilizar paredes interiores y exteriores.",
    price: 0,
    category: 'recubrimientos_decorativos' as CategoryKey,
    stock: 99,
    sku: 'MX013',
  },
  {
    id: 14,
    name: "TEXTUCOP",
    description: "Recubrimiento cementicio texturizado para decorar y proteger paredes interiores y exteriores.",
    price: 0,
    category: 'recubrimientos_decorativos' as CategoryKey,
    stock: 99,
    sku: 'MX014',
  },
  {
    id: 15,
    name: "Hormicop",
    description: "Mortero cementicio para terminaciones imitación hormigon\nsimbrado o entablonado o bien para reparacion de los mismos.",
    price: 0,
    category: 'recubrimientos_decorativos' as CategoryKey,
    stock: 99,
    sku: 'MX015',
  },
  {
    id: 16,
    name: "REPELLO 3 EN 1",
    description: "Mortero cementicio hidrófugo para revocar muros de mampostería y revoques gruesos.",
    price: 0,
    category: 'repellos' as CategoryKey,
    stock: 99,
    sku: 'MX016',
  },
  {
    id: 17,
    name: "MASILLA FIBRADA",
    description: "Mortero premezclado con fibra de vidrio para colocar sobre revoque frueso o aplanados en\nparedes de interiores y exteriores. Proporciona excelente\ntrabajabilidad y durabilidad prolongada. Ideal para\nacabados finos.",
    price: 0,
    category: 'repellos' as CategoryKey,
    stock: 99,
    sku: 'MX017',
  },
  {
    id: 18,
    name: "BASE COP FX",
    description: "Mezcla cementicia flexible para la realización de revoques en muros de construcción en seco (sistema EIFS). También puede utilizarse como adhesivo para placas de poliestireno expandido.",
    price: 0,
    category: 'repellos' as CategoryKey,
    stock: 99,
    sku: 'MX018',
  },
  {
    id: 19,
    name: "REPELLO TÉRMICO",
    description: "Mezcla cementicia con propiedades que permiten \nel aislamiento termico para la eficiencia y ahorro \nenergetico.",
    price: 0,
    category: 'repellos' as CategoryKey,
    stock: 99,
    sku: 'MX019',
  },
  {
    id: 20,
    name: "REPELLO IMPERMEABLE",
    description: "Mezcla cementicia con propiedades que le confieren excelente impermeabilidad y resistencia a la intemperie.",
    price: 0,
    category: 'repellos' as CategoryKey,
    stock: 99,
    sku: 'MX020',
  },
  {
    id: 21,
    name: "Impermeable de inmersión",
    description: "Mortero cementicio impermeable para recubrir techos, balcones, baños, piscinas, cisternas y tanques de agua.",
    price: 0,
    category: 'impermeabilizantes' as CategoryKey,
    stock: 99,
    sku: 'MX021',
  },
  {
    id: 22,
    name: "Anti Salitre",
    description: "Mortero cementicio con aditivos especiales para corregir o prevenir la aparición de eflorescencia o salitre.",
    price: 0,
    category: 'impermeabilizantes' as CategoryKey,
    stock: 99,
    sku: 'MX022',
  },
  {
    id: 23,
    name: "COPELASTIC MONOCOMPONENTE",
    description: "Mortero cementicio monocomponente con propiedades impermeables y flexibles, óptimo para reparaciones o impermeabilizaciones.",
    price: 0,
    category: 'impermeabilizantes' as CategoryKey,
    stock: 99,
    sku: 'MX023',
  },
  {
    id: 24,
    name: "Impercop Acrílico",
    description: "Impermeabilizante acrílico de alta resistencia y ultra flexible para techos y terrazas.",
    price: 0,
    category: 'impermeabilizantes' as CategoryKey,
    stock: 99,
    sku: 'MX024',
  },
  {
    id: 25,
    name: "Pega Cerámico",
    description: "Mezcla cementicia adhesiva para colocar cerámicos en pisos y paredes interiores.",
    price: 0,
    category: 'adhesivos' as CategoryKey,
    stock: 99,
    sku: 'MX025',
  },
  {
    id: 26,
    name: "Pega Porcelanato",
    description: "Mezcla cementicia adhesiva para colocar porcelanatos en pisos y paredes interiores y exteriores.",
    price: 0,
    category: 'adhesivos' as CategoryKey,
    stock: 99,
    sku: 'MX026',
  },
  {
    id: 27,
    name: "Piso sobre Piso FLEX",
    description: "Mezcla cementicia adhesiva flexible para pisos y paredes exteriores e interiores que requiera colocar piezas ceramicas y porcelanatos en grandes formatos.",
    price: 0,
    category: 'adhesivos' as CategoryKey,
    stock: 99,
    sku: 'MX027',
  },
  {
    id: 28,
    name: "Pega Block",
    description: "Mortero cementicio adhesivo para elevación de blocks y tabiques",
    price: 0,
    category: 'adhesivos' as CategoryKey,
    stock: 99,
    sku: 'MX028',
  },
  {
    id: 29,
    name: "PEGA MARMOL",
    description: "Mortero cementicio adhesivo ideal para usarse en la colocación de piezas de mármol y granito, de media y baja absorción",
    price: 0,
    category: 'adhesivos' as CategoryKey,
    stock: 99,
    sku: 'MX029',
  },
  {
    id: 30,
    name: "Junteador impermeable COP",
    description: "Mezcla cementicia impermeable para rellenar juntas entre piezas cerámicas.",
    price: 0,
    category: 'adhesivos' as CategoryKey,
    stock: 99,
    sku: 'MX030',
  },
  {
    id: 31,
    name: "LACA SOLVENTE",
    description: "Barniz base solvente que forma una pelicula brillosa o mate para proteger superficies  exteriores contra la abrasión y rayos UV",
    price: 0,
    category: 'selladores_barnices' as CategoryKey,
    stock: 99,
    sku: 'MX031',
  },
  {
    id: 32,
    name: "BARNIZCOP POLIURETANICO",
    description: "Barniz poliuretánico mate o brilloso de alta resistencia que otorga gran protección ideal para el tránsito liviano.",
    price: 0,
    category: 'selladores_barnices' as CategoryKey,
    stock: 99,
    sku: 'MX032',
  },
  {
    id: 33,
    name: "Cop Silicón base agua",
    description: "Sellador hidrófugo base agua incoloro para protección de piedra natural, premoldeados y ladrillos vistos.",
    price: 0,
    category: 'selladores_barnices' as CategoryKey,
    stock: 99,
    sku: 'MX033',
  },
  {
    id: 34,
    name: "Cop Silicón base solvente",
    description: "Sellador hidrófugo base solvente incoloro para protección de piedra natural, premoldeados y ladrillos vistos.",
    price: 0,
    category: 'selladores_barnices' as CategoryKey,
    stock: 99,
    sku: 'MX034',
  },
  {
    id: 35,
    name: "Plasticop",
    description: "Promotor de adherencia para la preparación de superficies lisas previa  a la aplicación de morteros.",
    price: 0,
    category: 'selladores_barnices' as CategoryKey,
    stock: 99,
    sku: 'MX035',
  },
  {
    id: 36,
    name: "Plastibond",
    description: "Sellador base agua para preparación de superficies previo a morteros y revestimientos.",
    price: 0,
    category: 'selladores_barnices' as CategoryKey,
    stock: 99,
    sku: 'MX036',
  },
  {
    id: 37,
    name: "SELLACOP INMERSION",
    description: "Sellador a base de resinas altamente hidrofugas para porteger revestimientos en inmersión o en constante contacto con el agua.",
    price: 0,
    category: 'selladores_barnices' as CategoryKey,
    stock: 99,
    sku: 'MX037',
  },
  {
    id: 38,
    name: "COP antiderrapante",
    description: "Promotor de adherencia resistente al agua para crear una textura antiderrapante en superficies resbalosas que esten en constante contacto con agua o humedad.",
    price: 0,
    category: 'selladores_barnices' as CategoryKey,
    stock: 99,
    sku: 'MX038',
  },
  {
    id: 39,
    name: "INTERCRIL",
    description: "Pintura acrilica al con color incorporado para decorar y proteger muros interiores",
    price: 0,
    category: 'pinturas_masillas' as CategoryKey,
    stock: 99,
    sku: 'MX039',
  },
  {
    id: 40,
    name: "Mastercril",
    description: "Pintura acrílica con color incorporado de alto poder cubritivo para proteger y decorar muros exteriores e interiores",
    price: 0,
    category: 'pinturas_masillas' as CategoryKey,
    stock: 99,
    sku: 'MX040',
  },
  {
    id: 41,
    name: "ACRILAC 5000H",
    description: "Pintura acrílica con color incorporado de alto poder cubritivo con propiedades impermeables y antihongos para proteger y decorar muros exteriores e interiores.",
    price: 0,
    category: 'pinturas_masillas' as CategoryKey,
    stock: 99,
    sku: 'MX041',
  },
  {
    id: 42,
    name: "ACRILPLUS 7000H",
    description: "Pintura acrilica de alta resistencia a la intemperie con color incorporado de alto poder cubritivo con propiedades impermeables y antihongos para proteger y decorar muros exteriores e interiores.",
    price: 0,
    category: 'pinturas_masillas' as CategoryKey,
    stock: 99,
    sku: 'MX042',
  },
  {
    id: 43,
    name: "COP ESMALTE",
    description: "Recubrimiento acrílico  base agua para protección de  metal, proporciona una excelente resistencia a la oxidacion y corrosion.",
    price: 0,
    category: 'pinturas_masillas' as CategoryKey,
    stock: 99,
    sku: 'MX043',
  },
  {
    id: 44,
    name: "TRAFICOP",
    description: "Pintura  acrílica diseñada especialmente para demarcación víal, señalamientos de estacionamientos ,cruces viales y símbolos.",
    price: 0,
    category: 'pinturas_masillas' as CategoryKey,
    stock: 99,
    sku: 'MX044',
  },
  {
    id: 45,
    name: "PINTURA DEPORTIVA",
    description: "Pintura  acrílica antiderrapante diseñada especialmente para demarcación y señalización de canchas deportivas",
    price: 0,
    category: 'pinturas_masillas' as CategoryKey,
    stock: 99,
    sku: 'MX045',
  },
  {
    id: 46,
    name: "PINTURA ALBERCAS",
    description: "Pintura  acrílica diseñada para decorar e impermeabilizar albercas",
    price: 0,
    category: 'pinturas_masillas' as CategoryKey,
    stock: 99,
    sku: 'MX046',
  },
  {
    id: 47,
    name: "Redimix Pasta",
    description: "Pasta blanca acrílica ideal para juntas en panelería ligera en tablas de yeso- cartón y corrección de imperfecciones en repellos.",
    price: 0,
    category: 'pinturas_masillas' as CategoryKey,
    stock: 99,
    sku: 'MX047',
  },
  {
    id: 48,
    name: "Redimix seco",
    description: "Recubrimiento cementicio flexible para emplearse en muros y plafones de tablaroca y tablacemento en interiores y exteriores.",
    price: 0,
    category: 'pinturas_masillas' as CategoryKey,
    stock: 99,
    sku: 'MX048',
  },
]

export const PRODUCTS: Product[] = RAW_PRODUCTS.map((p) => {
  const summary = TECHNICAL_SUMMARY_BY_ID[p.id]
  const product = { ...p } as Product
  if (summary) product.technicalSummary = summary
  product.technicalSheet = computeTechnicalSheet(product)
  if (IMAGE_BY_ID[p.id]) product.image = IMAGE_BY_ID[p.id]
  return product
})

export function getGalleryImagePathsById(_id: number): string[] { return [] }

export function getTechnicalSheetById(id: number): string | undefined {
  return PRODUCTS.find((p) => p.id === id)?.technicalSheet
}

export function getTechnicalSummaryById(id: number): TechnicalSummary | undefined {
  return PRODUCTS.find((p) => p.id === id)?.technicalSummary
}

export function productHidesDetailDescription(id: number): boolean {
  return PRODUCTS.find((p) => p.id === id)?.hideDetailDescription === true
}
